scrape_configs:
  - job_name: 'service_monitoring'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['bff-authors-service:8081','bff-books-service:8082']
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080','node-exporter:9100']
